### ISSUE TITLE
Aeon MultiSensor 6

### ISSUE THREAD

**Issue by TechnicallyBob202** [TheFuzz4/SmartThingsSplunkLogger#5]
I added some Aeon MultiSensors, and I'm not getting any updates from them in Splunk. I see the updates in the ST logs, but nothing is coming through the HEC.

**Comment by TechnicallyBob202** [comment]
Correction!  I'm seeing motion events, but no temperature, humidity or illuminance.

**Comment by TheFuzz4** [comment]
Are you seeing temp and humidity now but not lux correct?

**Comment by TechnicallyBob202** [comment]
I stopped collecting from it, because it just wasn't working.  I bought a zooZ mini sensor, and it's working like a champ!
